server:
  port: 50022

spring:
  application:
    name: cloud-user-manage
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root