server:
  port: 50010

spring:
  application:
    name: cloud-roles-manage
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    # 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://222.200.99.204:3307/db01?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    # redis配置
  redis:
    database: 0
    host: 222.200.99.204
    #redis默认端口
    port: 6379
    password:
    timeout: 5000ms